# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvwi/wt/releases/download/v1.3.0/wt_1.3.0_darwin_amd64.tar.gz"
      sha256 "e958bb83f089efef53ba348bdaf91f554cf9e85d8cfc508d7a521a6832de252d"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvwi/wt/releases/download/v1.3.0/wt_1.3.0_darwin_arm64.tar.gz"
      sha256 "efdd5a8090d5fc98d6f14815cd5a04f13ce037f2d2124cd9b4a21e014616d119"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v1.3.0/wt_1.3.0_linux_amd64.tar.gz"
      sha256 "fcefcb0f316ed7df0a97ac4d2663a260ab5167f1599ccc8f62efcf99ca9db1fe"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v1.3.0/wt_1.3.0_linux_arm64.tar.gz"
      sha256 "88f2275965e10afd1f639f282f14a1a6a1cbedeaa24b16d46374322077909df7"
      def install
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for 'wt switch' and 'wt new' to change directories):

        Fish:  Add to ~/.config/fish/config.fish:
               wt init-shell fish | source

        Bash:  Add to ~/.bashrc:
               eval "$(wt init-shell bash)"

        Zsh:   Add to ~/.zshrc:
               eval "$(wt init-shell zsh)"

      To generate shell completions:
        wt completion fish | source
        eval "$(wt completion bash)"
        eval "$(wt completion zsh)"
    EOS
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
