# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvwi/wt/releases/download/v0.9.2/wt_0.9.2_darwin_amd64.tar.gz"
      sha256 "4e9fed6fa468b7a861aec690c737964dade1896e03afd8546362d7b3ba0b2f6a"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvwi/wt/releases/download/v0.9.2/wt_0.9.2_darwin_arm64.tar.gz"
      sha256 "ea2e0ea13cd274bfbc8613010c43645152ce137a2869f6a60740c3da401f33b3"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v0.9.2/wt_0.9.2_linux_amd64.tar.gz"
      sha256 "746ecf100a396b692e4f09d90cbceb7d88fc240bb85752272b540a74b29e4d5e"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v0.9.2/wt_0.9.2_linux_arm64.tar.gz"
      sha256 "51437d065fa3d498766fee35e9fd0313cc71405d9327d9fc07b922b8d49e625b"
      def install
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for 'wt switch' and 'wt new' to change directories):

        Fish:  Add to ~/.config/fish/config.fish:
               wt init-shell fish | source

        Bash:  Add to ~/.bashrc:
               eval "$(wt init-shell bash)"

        Zsh:   Add to ~/.zshrc:
               eval "$(wt init-shell zsh)"

      To generate shell completions:
        wt completion fish | source
        eval "$(wt completion bash)"
        eval "$(wt completion zsh)"
    EOS
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
