# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvwi/wt/releases/download/v0.7.0/wt_0.7.0_darwin_amd64.tar.gz"
      sha256 "b921f192099ab8d9b3f8b0ae951ae1759d78e0c1cd574d26981460a358e704af"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvwi/wt/releases/download/v0.7.0/wt_0.7.0_darwin_arm64.tar.gz"
      sha256 "edb1592722bc7b8c7121bb954f74119665f873f9a72692f6426293c8ba40f84e"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v0.7.0/wt_0.7.0_linux_amd64.tar.gz"
      sha256 "f8fe764e2885fe40bf4af0b7491231ef59e2dcb4c0c082d81955b6df808aeced"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvwi/wt/releases/download/v0.7.0/wt_0.7.0_linux_arm64.tar.gz"
      sha256 "6b9d632ea347bae4dd746561f2acbf83775ff85db434d18e7b319854d124b410"
      def install
        bin.install "wt"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for 'wt switch' and 'wt new' to change directories):

        Fish:  Add to ~/.config/fish/config.fish:
               wt init-shell fish | source

        Bash:  Add to ~/.bashrc:
               eval "$(wt init-shell bash)"

        Zsh:   Add to ~/.zshrc:
               eval "$(wt init-shell zsh)"

      To generate shell completions:
        wt completion fish | source
        eval "$(wt completion bash)"
        eval "$(wt completion zsh)"
    EOS
  end

  test do
    system "#{bin}/wt", "--version"
  end
end
