# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "1.19.1"

  on_macos do
    on_intel do
      sha256 "8c9d65c65ea4f073dc37765e63f731e436e430c0576197a6dc4fd19ca9dfe666"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mvwi/wt/"
    end
    on_arm do
      sha256 "5ea7930f2fe25ffb0df11d0e943fc2e9df088a4334489de0c262a8b73ba59bf0"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mvwi/wt/"
    end
  end

  on_linux do
    on_intel do
      sha256 "96bd6b296d2c245e56e34791ceee45659b0ae236e2cd76ead1574d6ce9167e4c"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mvwi/wt/"
    end
    on_arm do
      sha256 "46cfb08f4f029523de07f9669b3ef4d0dd9a625a3cfdc4107573478238047cea"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mvwi/wt/"
    end
  end

  name "wt"
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
  end

  # No zap stanza required

  caveats <<~EOS
    To enable shell integration (required for 'wt switch' and 'wt new' to change directories):

      Fish:  Add to ~/.config/fish/config.fish:
             wt init-shell fish | source

      Bash:  Add to ~/.bashrc:
             eval \"$(wt init-shell bash)\"

      Zsh:   Add to ~/.zshrc:
             eval \"$(wt init-shell zsh)\"

    To generate shell completions:
      wt completion fish | source
      eval \"$(wt completion bash)\"
      eval \"$(wt completion zsh)\"
  EOS
end
