# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "1.22.0"

  on_macos do
    on_arm do
      sha256 "e90900487bee720a8757045e6d4f8397cd215a932b62da6e4246614a23b20154"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f7e2bb676c51e57d0b1bfe8627733267250c1ab38fb9a494a8288373ac98cbe"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c41467bba64838dd4241c46023def535d0d5ad0939faad0a58e955c5246e16fe"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad2fd8982c5fbe391e19aa24f0361d81df5532e1566fdf6c8740ea1963bcbf63"
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wt"
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
  end

  # No zap stanza required

  caveats <<~EOS
    To enable shell integration (required for 'wt switch' and 'wt new' to change directories):

      Fish:  Add to ~/.config/fish/config.fish:
             wt init-shell fish | source

      Bash:  Add to ~/.bashrc:
             eval \"$(wt init-shell bash)\"

      Zsh:   Add to ~/.zshrc:
             eval \"$(wt init-shell zsh)\"

    To generate shell completions:
      wt completion fish | source
      eval \"$(wt completion bash)\"
      eval \"$(wt completion zsh)\"
  EOS
end
