# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Git worktree manager - streamlined workflow for feature branches"
  homepage "https://github.com/mvwi/wt"
  version "1.8.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mvwi/wt/"
      sha256 "1964ab05d1b7020dd6c3d84bacf2bf52c0535f174b64c227c734ac57c57bc9bb"
    end
    on_arm do
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mvwi/wt/"
      sha256 "0c9bce47e49ad7849be8e99f4522b9585864fcede85fa13a3f48cbb9a481de8c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mvwi/wt/"
      sha256 "72bcfff62fa5f2995c7b9763c71ecc9246ddc0c9062789f45b22c26b2f9680a9"
    end
    on_arm do
      url "https://github.com/mvwi/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mvwi/wt/"
      sha256 "43c68858fb962fab1d5cc742a00ba6d944555511e71c68f90642af550e23eb74"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
  end

  caveats do
    "To enable shell integration (required for 'wt switch' and 'wt new' to change directories):"
    ""
    "  Fish:  Add to ~/.config/fish/config.fish:"
    "         wt init-shell fish | source"
    ""
    "  Bash:  Add to ~/.bashrc:"
    "         eval \"$(wt init-shell bash)\""
    ""
    "  Zsh:   Add to ~/.zshrc:"
    "         eval \"$(wt init-shell zsh)\""
    ""
    "To generate shell completions:"
    "  wt completion fish | source"
    "  eval \"$(wt completion bash)\""
    "  eval \"$(wt completion zsh)\""
  end

  # No zap stanza required
end
